language: objective-c
osx_image: xcode11.3
before_install:
- brew install gnu-sed curl jq grep
- export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:$PATH"
- export LC_ALL=en_US.UTF-8
- git config --global user.email "maxime.colmant@gmail.com"
- git config --global user.name "Maxime Colmant"
- gem install cocoapods xcpretty jazzy --no-document --quiet
install: true
script: bash ci/script.sh
deploy:
- provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "./iosdoc.zip"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: "JQdMjEjdyeugQ08tDDBrdEt46r7Vpr76Zx06ckNwAQV/+PL7qG6JQkLF4+8p7rtUnALJUzUxDlh6V4YPBRGJq2JBIGO9pBf3AoVSwSvR64oT3EkO+2TuWHBd5zFhW4W2WfwgMCWfzCtQj5KXXQgAKVzFKzV/sj70VXJzG99GgTRv3PwLvG0TSho8uMe1fmKZh3sfBIw9SQd/dAvxwHFGDl90C3bTJMBBXeg3JOAV1IWjRsBYzYeid1ZEAZpDhj5j+BKlkycF7YgVtrDP0zerJ72aPSGPVNDWQkfRZT/QKL8fWKr5cI+4Fvo9QkVYxC8QwHhn8UxYCbPb/sld31RmMNycLKR79dRMMzwskYcNs0r628MVUNAQ/vKjji2IA+7jB19CwXd53tUUBLWJNx2KslTeq1Kb1ibvb3uNnwby7yvPqUcDdks7wQ4RguWBY6nB5lKRKZR0COUY6VrEn59pvzMjdEUUkwEXSl2nlz8d0g5KBM/e8F2+j/NKqULI9TFScp1/rahKHTr91P4Fu2xFumg0gOyYLtX92O3zeKMsaCTmvVP0CJmA9fZANe8MYvwaO7pg3VgXumR6pHqaLHL2rZTY+I7H+PlygJc4Z6IHUddFxZQmtdpNLmOXFhnuS77jVihzZkiZgLUTh4YVAdLMcZvYhQzObhgHDU25Sdqryh8=" # GITHUB_TOKEN
